name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      # リポジトリのチェックアウトをする。
      - name: Check out repository code
        uses: actions/checkout@v3
