name: TerraformDestroy

on:
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: ap-northeast-1
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  TF_VERSION: 1.6.0
  WORK_DIR: ./environments/prod

permissions:
  id-token: write
  contents: read
  actions: read
  pull-requests: write

jobs:
  Terraform_Apply:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      # リポジトリのチェックアウトをする。
      - name: Check out repository code
        uses: actions/checkout@v3

      # OICDでAssumeRoleをする。
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}

      - name: Setup Terraform
        # バージョン2を使用する
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Exec Terraform init
        id: init
        working-directory: "${{ env.WORK_DIR }}"
        run: terraform init

      - name: terraform destroy
        id: destroy
        working-directory: "${{ env.WORK_DIR }}"
        run: terraform destroy -auto-approve
